# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160213115339 on 2016-02-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_artikel', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Judul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.AddField(
            model_name='artikel',
            name='judul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Judul'),
        ),
    ]
